### ISSUE TITLE
paket.unity3d.references items not trimmed

### ISSUE THREAD

**Issue by doubleday** [wooga/atlas-paket#54]
## Description

Items with training spaces in paket.unity3d.references are silently ignored

## Steps to reproduce

1. Add some whitespace to an entry and run ./gradlew paketInstall ...

**Comment by Larusso** [comment]
A good place to start is here:

https://github.com/wooga/atlas-paket/blob/c909d96b56c816aa741533df7c3a56a02e0f751e/src/main/groovy/wooga/gradle/paket/base/utils/internal/PaketUnityReferences.groovy#L28-L36
